# Auto-generated by cppast2autopxd 0.1.0 from octree_pointcloud_changedetector.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/octree/octree_pointcloud_changedetector.h" namespace "pcl::octree" nogil:
    cdef cppclass OctreePointCloudChangeDetector[PointT]:
        OctreePointCloudChangeDetector(double resolution) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void addPointsFromInputCloud() except +
        void deleteTree() except +
        void switchBuffers() except +
        double getResolution() except +
        unsigned int getTreeDepth() except +
        int getPointIndicesFromNewVoxels(vector[int]& indices) except +
        int getPointIndicesFromNewVoxels(vector[int]& indices, int min_points_per_leaf) except +
