# Auto-generated by cppast2autopxd 0.1.0 from octree_search.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/octree/octree_search.h" namespace "pcl::octree" nogil:
    cdef cppclass OctreePointCloudSearch[PointT]:
        OctreePointCloudSearch(double resolution) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void addPointsFromInputCloud() except +
        void defineBoundingBox() except +
        void defineBoundingBox(double min_x, double min_y, double min_z, double max_x, double max_y, double max_z) except +
        void deleteTree() except +
        double getResolution() except +
        unsigned int getTreeDepth() except +
        bool voxelSearch(const PointT& point, vector[int]& point_idx_data) except +
        int nearestKSearch(const PointT& p_q, int k, vector[int]& k_indices, vector[float]& k_sqr_distances) except +
        int radiusSearch(const PointT& p_q, double radius, vector[int]& k_indices, vector[float]& k_sqr_distances) except +
        int radiusSearch(const PointT& p_q, double radius, vector[int]& k_indices, vector[float]& k_sqr_distances, unsigned int max_nn) except +
        void approxNearestSearch(const PointT& p_q, int& result_index, float& sqr_distance) except +
