# Auto-generated by cppast2autopxd 0.1.0 from concave_hull.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.vertices cimport Vertices

cdef extern from "pcl/surface/concave_hull.h" namespace "pcl" nogil:
    cdef cppclass ConcaveHull[PointInT]:
        ConcaveHull() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setAlpha(double alpha) except +
        double getAlpha() except +
        void setDimension(int dimension) except +
        int getDimension() except +
        void reconstruct(PointCloud[PointInT]& points) except +
        void reconstruct(PointCloud[PointInT]& points, vector[Vertices]& polygons) except +
