# Auto-generated by cppast2autopxd 0.1.0 from convex_hull.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/surface/convex_hull.h" namespace "pcl" nogil:
    cdef cppclass ConvexHull[PointInT]:
        ConvexHull() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setDimension(int dimension) except +
        int getDimension() except +
        void setComputeAreaVolume(bool value) except +
        double getTotalArea() except +
        double getTotalVolume() except +
        void reconstruct(PointCloud[PointInT]& points) except +
