# Auto-generated by cppast2autopxd 0.1.0 from gp3.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.vertices cimport Vertices

cdef extern from "pcl/surface/gp3.h" namespace "pcl" nogil:
    cdef cppclass GreedyProjectionTriangulation[PointInT]:
        GreedyProjectionTriangulation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void reconstruct(vector[Vertices]& polygons) except +
        void setSearchRadius(double radius) except +
        double getSearchRadius() except +
        void setMu(double mu) except +
        double getMu() except +
        void setMaximumNearestNeighbors(int nnn) except +
        int getMaximumNearestNeighbors() except +
        void setMaximumSurfaceAngle(double eps_angle) except +
        double getMaximumSurfaceAngle() except +
        void setMinimumAngle(double minimum_angle) except +
        double getMinimumAngle() except +
        void setMaximumAngle(double maximum_angle) except +
        double getMaximumAngle() except +
        void setNormalConsistency(bool consistent) except +
        bool getNormalConsistency() except +
        void setConsistentVertexOrdering(bool consistent_ordering) except +
        bool getConsistentVertexOrdering() except +
