# Auto-generated by cppast2autopxd 0.1.0 from mls.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/surface/mls.h" namespace "pcl" nogil:
    cdef cppclass MovingLeastSquares[PointInT, PointOutT]:
        MovingLeastSquares() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setSearchRadius(double radius) except +
        double getSearchRadius() except +
        void setPolynomialOrder(int order) except +
        int getPolynomialOrder() except +
        void setComputeNormals(bool compute_normals) except +
        void setSqrGaussParam(double sqr_gauss_param) except +
        double getSqrGaussParam() except +
        void setNumberOfThreads(unsigned int threads) except +
        void process(PointCloud[PointOutT]& output) except +
