# Auto-generated by cppast2autopxd 0.1.0 from grabber.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string

cdef extern from "pcl/io/grabber.h" namespace "pcl" nogil:
    cdef cppclass Grabber:
        void start() except +
        void stop() except +
        bool isRunning() except +
        string getName() except +
        float getFramesPerSecond() except +
