# Auto-generated by cppast2autopxd 0.1.0 from hdl_grabber.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string

cdef extern from "pcl/io/hdl_grabber.h" namespace "pcl" nogil:
    cdef cppclass HDLGrabber:
        HDLGrabber() except +
        HDLGrabber(const string& correctionsFile) except +
        HDLGrabber(const string& correctionsFile, const string& pcapFile) except +
        void start() except +
        void stop() except +
        bool isRunning() except +
        string getName() except +
        float getFramesPerSecond() except +
        void setMinimumDistanceThreshold(float& minThreshold) except +
        void setMaximumDistanceThreshold(float& maxThreshold) except +
        float getMinimumDistanceThreshold() except +
        float getMaximumDistanceThreshold() except +
        unsigned char getMaximumNumberOfLasers() except +
