# Auto-generated by cppast2autopxd 0.1.0 from pcd_grabber.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector

cdef extern from "pcl/io/pcd_grabber.h" namespace "pcl" nogil:
    cdef cppclass PCDGrabber[PointT]:
        PCDGrabber(const string& pcd_path) except +
        PCDGrabber(const string& pcd_path, float frames_per_second) except +
        PCDGrabber(const string& pcd_path, float frames_per_second, bool repeat) except +
        PCDGrabber(const vector[string]& pcd_files) except +
        PCDGrabber(const vector[string]& pcd_files, float frames_per_second) except +
        PCDGrabber(const vector[string]& pcd_files, float frames_per_second, bool repeat) except +
        void start() except +
        void stop() except +
        bool isRunning() except +
        string getName() except +
        float getFramesPerSecond() except +
        void trigger() except +
        void rewind() except +
        size_t numFrames() except +
