# Auto-generated by cppast2autopxd 0.1.0 from ply_io.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/io/ply_io.h" namespace "pcl::io" nogil:
    int loadPLYFile[PointT](const string& file_name, PointCloud[PointT]& cloud) except +

    int savePLYFile[PointT](const string& file_name, const PointCloud[PointT]& cloud) except +
    int savePLYFile[PointT](const string& file_name, const PointCloud[PointT]& cloud, bool binary_mode) except +

    int savePLYFileASCII[PointT](const string& file_name, const PointCloud[PointT]& cloud) except +

    int savePLYFileBinary[PointT](const string& file_name, const PointCloud[PointT]& cloud) except +
