#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""python-pcl_skbuild: PCL Python bindings built with scikit-build.

Structure follows sirokujira/cython-scikit-build-template; the Cython extern
declarations under src/pcl/pxd/ are auto-generated by cppast2autopxd.
"""
import platform

from setuptools import find_packages
from skbuild import setup

install_requires = [
    'numpy',
]

if platform.system() == 'Windows':
    CMAKE_ARGS = ['-DCMAKE_C_COMPILER=cl.exe', '-DCMAKE_CXX_COMPILER=cl.exe']
elif platform.system() == 'Darwin':
    CMAKE_ARGS = ['-DCMAKE_C_COMPILER=clang', '-DCMAKE_CXX_COMPILER=clang++']
else:
    CMAKE_ARGS = ['-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++']

setup(
    name='python-pcl-skbuild',
    description='PCL (Point Cloud Library) Python bindings, '
                'scikit-build + Cython + cppast2autopxd',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/sirokujira/python-pcl_skbuild',
    version='0.1.0',
    author='Tooru Oonuma',
    author_email='t753github@gmail.com',
    maintainer='Tooru Oonuma',
    maintainer_email='t753github@gmail.com',
    license='MIT',
    cmake_args=CMAKE_ARGS,
    packages=find_packages(
        'src',
        exclude=["*.tests", "*.tests.*", "tests.*", "tests"],
    ),
    package_dir={'': 'src'},
    package_data={'pcl.pxd': ['*.pxd'], 'pcl': ['*.pxd']},
    zip_safe=False,
    install_requires=install_requires,
    python_requires='>=3.9',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: C++',
        'Topic :: Scientific/Engineering',
    ],
)
