# Auto-generated by cppast2autopxd 0.1.0 from conditional_euclidean_clustering.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/segmentation/conditional_euclidean_clustering.h" namespace "pcl" nogil:
    cdef cppclass ConditionalEuclideanClustering[PointT]:
        ConditionalEuclideanClustering() except +
        ConditionalEuclideanClustering(bool extract_removed_clusters) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setClusterTolerance(float cluster_tolerance) except +
        float getClusterTolerance() except +
        void setMinClusterSize(int min_cluster_size) except +
        int getMinClusterSize() except +
        void setMaxClusterSize(int max_cluster_size) except +
        int getMaxClusterSize() except +
        void segment(vector[PointIndices]& clusters) except +
