# Auto-generated by cppast2autopxd 0.1.0 from extract_clusters.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/segmentation/extract_clusters.h" namespace "pcl" nogil:
    cdef cppclass EuclideanClusterExtraction[PointT]:
        EuclideanClusterExtraction() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setClusterTolerance(double tolerance) except +
        double getClusterTolerance() except +
        void setMinClusterSize(int min_cluster_size) except +
        int getMinClusterSize() except +
        void setMaxClusterSize(int max_cluster_size) except +
        int getMaxClusterSize() except +
        void extract(vector[PointIndices]& clusters) except +
