# Auto-generated by cppast2autopxd 0.1.0 from min_cut_segmentation.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/segmentation/min_cut_segmentation.h" namespace "pcl" nogil:
    cdef cppclass MinCutSegmentation[PointT]:
        MinCutSegmentation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setForegroundPoints(const shared_ptr[PointCloud[PointT]]& foreground_points) except +
        void setSigma(double sigma) except +
        double getSigma() except +
        void setRadius(double radius) except +
        double getRadius() except +
        void setSourceWeight(double weight) except +
        double getSourceWeight() except +
        void setNumberOfNeighbours(unsigned int neighbour_number) except +
        unsigned int getNumberOfNeighbours() except +
        double getMaxFlow() except +
        void extract(vector[PointIndices]& clusters) except +
