# Auto-generated by cppast2autopxd 0.1.0 from progressive_morphological_filter.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/segmentation/progressive_morphological_filter.h" namespace "pcl" nogil:
    cdef cppclass ProgressiveMorphologicalFilter[PointT]:
        ProgressiveMorphologicalFilter() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setMaxWindowSize(int max_window_size) except +
        int getMaxWindowSize() except +
        void setSlope(float slope) except +
        float getSlope() except +
        void setMaxDistance(float max_distance) except +
        float getMaxDistance() except +
        void setInitialDistance(float initial_distance) except +
        float getInitialDistance() except +
        void setCellSize(float cell_size) except +
        float getCellSize() except +
        void setBase(float base) except +
        float getBase() except +
        void setExponential(bool exponential) except +
        bool getExponential() except +
        void extract(vector[int]& ground) except +
