# Auto-generated by cppast2autopxd 0.1.0 from sac_segmentation.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.model_coefficients cimport ModelCoefficients
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/segmentation/sac_segmentation.h" namespace "pcl" nogil:
    cdef cppclass SACSegmentation[PointT]:
        SACSegmentation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setModelType(int model) except +
        int getModelType() except +
        void setMethodType(int method) except +
        int getMethodType() except +
        void setDistanceThreshold(double threshold) except +
        double getDistanceThreshold() except +
        void setMaxIterations(int max_iterations) except +
        int getMaxIterations() except +
        void setProbability(double probability) except +
        double getProbability() except +
        void setOptimizeCoefficients(bool optimize) except +
        bool getOptimizeCoefficients() except +
        void setRadiusLimits(const double& min_radius, const double& max_radius) except +
        void setEpsAngle(double ea) except +
        double getEpsAngle() except +
        void segment(PointIndices& inliers, ModelCoefficients& model_coefficients) except +
