# Auto-generated by cppast2autopxd 0.1.0 from sac_segmentation_normals.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.model_coefficients cimport ModelCoefficients
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/segmentation/sac_segmentation.h" namespace "pcl" nogil:
    cdef cppclass SACSegmentationFromNormals[PointT, PointNT]:
        SACSegmentationFromNormals() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setModelType(int model) except +
        void setMethodType(int method) except +
        void setDistanceThreshold(double threshold) except +
        void setMaxIterations(int max_iterations) except +
        void setOptimizeCoefficients(bool optimize) except +
        void setProbability(double probability) except +
        void setRadiusLimits(const double& min_radius, const double& max_radius) except +
        void setEpsAngle(double ea) except +
        double getEpsAngle() except +
        void segment(PointIndices& inliers, ModelCoefficients& model_coefficients) except +
        void setInputNormals(const shared_ptr[PointCloud[PointNT]]& normals) except +
        void setNormalDistanceWeight(double distance_weight) except +
        double getNormalDistanceWeight() except +
        void setMinMaxOpeningAngle(const double& min_angle, const double& max_angle) except +
        void setDistanceFromOrigin(const double d) except +
        double getDistanceFromOrigin() except +
