# Auto-generated by cppast2autopxd 0.1.0 from harris_3d.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/keypoints/harris_3d.h" namespace "pcl" nogil:
    cdef cppclass HarrisKeypoint3D[PointInT, PointOutT]:
        enum ResponseMethod:
            HARRIS = 0
            NOBLE = 0
            LOWE = 0
            TOMASI = 0
            CURVATURE = 0
        HarrisKeypoint3D() except +
        HarrisKeypoint3D(ResponseMethod method, float radius, float threshold) except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void compute(PointCloud[PointOutT]& output) except +
        void setMethod(ResponseMethod type) except +
        void setRadius(float radius) except +
        void setThreshold(float threshold) except +
        void setNonMaxSupression(bool suppress) except +
        void setRefine(bool do_refine) except +
        void setNumberOfThreads(unsigned int nr_threads) except +
