# Auto-generated by cppast2autopxd 0.1.0 from ModelCoefficients.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector

cdef extern from "pcl/ModelCoefficients.h" namespace "pcl" nogil:
    cdef cppclass ModelCoefficients:
        ctypedef shared_ptr[ModelCoefficients] Ptr
        ctypedef shared_ptr[const ModelCoefficients] ConstPtr
        vector[float] values
