# Auto-generated by cppast2autopxd 0.1.0 from pcd_io.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/io/pcd_io.h" namespace "pcl::io" nogil:
    int loadPCDFile[PointT](const string& file_name, PointCloud[PointT]& cloud) except +

    int savePCDFile[PointT](const string& file_name, const PointCloud[PointT]& cloud) except +
    int savePCDFile[PointT](const string& file_name, const PointCloud[PointT]& cloud, bool binary_mode) except +

    int savePCDFileASCII[PointT](const string& file_name, const PointCloud[PointT]& cloud) except +

    int savePCDFileBinary[PointT](const string& file_name, PointCloud[PointT]& cloud) except +
