# Auto-generated by cppast2autopxd 0.1.0 from PointIndices.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector

cdef extern from "pcl/PointIndices.h" namespace "pcl" nogil:
    cdef cppclass PointIndices:
        ctypedef shared_ptr[PointIndices] Ptr
        ctypedef shared_ptr[const PointIndices] ConstPtr
        vector[int] indices
