# Auto-generated by cppast2autopxd 0.1.0 from point_cloud.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector

cdef extern from "pcl/point_cloud.h" namespace "pcl" nogil:
    cdef cppclass PointCloud[PointT]:
        ctypedef shared_ptr[PointCloud[PointT]] Ptr
        ctypedef shared_ptr[const PointCloud[PointT]] ConstPtr
        PointCloud() except +
        PointCloud(unsigned int width_, unsigned int height_) except +
        vector[PointT] points
        unsigned int width
        unsigned int height
        bool is_dense
        size_t size() except +
        bool empty() except +
        void clear() except +
        void reserve(size_t n) except +
        void resize(size_t count) except +
        void push_back(const PointT& pt) except +
        PointT& at(size_t n) except +
        PointT& front() except +
        PointT& back() except +
        PointT& operator[](size_t n) except +
        bool isOrganized() except +
        void swap(PointCloud[PointT]& rhs) except +
