# Auto-generated by cppast2autopxd 0.1.0 from Vertices.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector

cdef extern from "pcl/Vertices.h" namespace "pcl" nogil:
    cdef cppclass Vertices:
        ctypedef shared_ptr[Vertices] Ptr
        ctypedef shared_ptr[const Vertices] ConstPtr
        Vertices() except +
        vector[int] vertices
