# Auto-generated by cppast2autopxd 0.1.0 from condition_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.string cimport string
from pcl.pxd.filters.conditional_removal cimport ConditionAnd, ConditionalRemoval
from pcl.pxd.point_types cimport PointXYZ

cdef extern from "pcl/compat/condition_args.h" namespace "pclcompat" nogil:
    const int COMPARE_GT

    const int COMPARE_GE

    const int COMPARE_LT

    const int COMPARE_LE

    const int COMPARE_EQ

    shared_ptr[ConditionAnd[PointXYZ]] makeConditionAnd() except +

    void addFieldComparison(ConditionAnd[PointXYZ]& condition, const string& field_name, int op, double value) except +

    void setCondition(ConditionalRemoval[PointXYZ]& filter, shared_ptr[ConditionAnd[PointXYZ]] condition) except +
