# Auto-generated by cppast2autopxd 0.1.0 from global_alignment_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ

cdef extern from "pcl/compat/global_alignment_args.h" namespace "pclcompat" nogil:
    bool globalAlignment(const shared_ptr[PointCloud[PointXYZ]]& source, const vector[float]& source_features, const shared_ptr[PointCloud[PointXYZ]]& target, const vector[float]& target_features, int max_iterations, int number_of_samples, int correspondence_randomness, float similarity_threshold, float max_correspondence_distance, float inlier_fraction, PointCloud[PointXYZ]& out_aligned, float* out_matrix16, vector[int]& out_inliers, double* out_fitness) except +
