# Auto-generated by cppast2autopxd 0.1.0 from grabber_callback.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.io.hdl_grabber cimport HDLGrabber
from pcl.pxd.io.pcd_grabber cimport PCDGrabber
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ

cdef extern from "pcl/compat/grabber_callback.h" namespace "pclcompat" nogil:
    ctypedef void (*CloudCallbackFn)(shared_ptr[PointCloud[PointXYZ]] cloud, void* user_data)

    cdef cppclass CloudCallback:
        CloudCallback() except +
        void connect(PCDGrabber[PointXYZ]* grabber, CloudCallbackFn fn, void* user_data) except +
        void connect(HDLGrabber* grabber, CloudCallbackFn fn, void* user_data) except +
        void disconnect() except +
        bool connected() except +
