# Auto-generated by cppast2autopxd 0.1.0 from keypoint_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from pcl.pxd.keypoints.harris_3d cimport HarrisKeypoint3D
from pcl.pxd.point_types cimport PointXYZ, PointXYZI

cdef extern from "pcl/compat/keypoint_args.h" namespace "pclcompat" nogil:
    const int HARRIS_METHOD_HARRIS

    const int HARRIS_METHOD_NOBLE

    const int HARRIS_METHOD_LOWE

    const int HARRIS_METHOD_TOMASI

    const int HARRIS_METHOD_CURVATURE

    void setHarrisMethod(HarrisKeypoint3D[PointXYZ, PointXYZI]& detector, int method) except +
