# Auto-generated by cppast2autopxd 0.1.0 from matching_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.vector cimport vector

cdef extern from "pcl/compat/matching_args.h" namespace "pclcompat" nogil:
    int matchFpfhDescriptors(const vector[float]& model, const vector[float]& scene, float max_distance, vector[int]& out_model_indices, vector[int]& out_scene_indices, vector[float]& out_distances) except +

    int matchShotDescriptors(const vector[float]& model, const vector[float]& scene, float max_distance, vector[int]& out_model_indices, vector[int]& out_scene_indices, vector[float]& out_distances) except +
