# Auto-generated by cppast2autopxd 0.1.0 from mesh_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ

cdef extern from "pcl/compat/mesh_args.h" namespace "pclcompat" nogil:
    const int MESH_FORMAT_PLY

    const int MESH_FORMAT_OBJ

    const int MESH_FORMAT_VTK

    int saveMesh(const string& path, const PointCloud[PointXYZ]& cloud, const vector[int]& indices, const vector[int]& counts, int format, bool binary) except +

    int loadMesh(const string& path, int format, PointCloud[PointXYZ]& out_cloud, vector[int]& out_indices, vector[int]& out_counts) except +
