# Auto-generated by cppast2autopxd 0.1.0 from organized_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from pcl.pxd.features.integral_image_normal cimport IntegralImageNormalEstimation
from pcl.pxd.point_types cimport PointXYZ, Normal
from pcl.pxd.segmentation.conditional_euclidean_clustering cimport ConditionalEuclideanClustering

cdef extern from "pcl/compat/organized_args.h" namespace "pclcompat" nogil:
    const int IINE_COVARIANCE_MATRIX

    const int IINE_AVERAGE_3D_GRADIENT

    const int IINE_AVERAGE_DEPTH_CHANGE

    const int IINE_SIMPLE_3D_GRADIENT

    void setNormalEstimationMethod(IntegralImageNormalEstimation[PointXYZ, Normal]& estimator, int method) except +

    ctypedef bool (*ClusterConditionFn)(const PointXYZ& a, const PointXYZ& b, float squared_distance, void* user_data)

    void setClusterCondition(ConditionalEuclideanClustering[PointXYZ]& clustering, ClusterConditionFn fn, void* user_data) except +
