# Auto-generated by cppast2autopxd 0.1.0 from people_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.vector cimport vector

cdef extern from "pcl/compat/people_args.h" namespace "pclcompat" nogil:
    int hogDescriptorSize(int h, int w, int bin_size, int n_orients) except +

    int hogCompute(vector[float]& image, int h, int w, int n_channels, int bin_size, int n_orients, bool soft_bin, vector[float]& out) except +
