# Auto-generated by cppast2autopxd 0.1.0 from range_image_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.range_image.range_image cimport RangeImage

cdef extern from "pcl/compat/range_image_args.h" namespace "pclcompat" nogil:
    const int RANGE_IMAGE_CAMERA_FRAME

    const int RANGE_IMAGE_LASER_FRAME

    shared_ptr[RangeImage] makeRangeImage(const PointCloud[PointXYZ]& cloud, float angular_resolution, float max_angle_width, float max_angle_height, int coordinate_frame, float noise_level, float min_range, int border_size) except +

    void rangeImageSetUnseenToMaxRange(RangeImage& image) except +

    int rangeImageWidth(const RangeImage& image) except +

    int rangeImageHeight(const RangeImage& image) except +

    void rangeImageRanges(const RangeImage& image, vector[float]& out) except +

    void rangeImagePoints(const RangeImage& image, vector[PointXYZ]& out) except +

    int narfKeypoints(RangeImage& image, float support_size, bool add_points_on_straight_edges, vector[int]& out) except +
