# Auto-generated by cppast2autopxd 0.1.0 from sac_models.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.sample_consensus.ransac cimport RandomSampleConsensus
from pcl.pxd.sample_consensus.sac_model cimport SampleConsensusModel

cdef extern from "pcl/compat/sac_models.h" namespace "pclcompat" nogil:
    shared_ptr[SampleConsensusModel[PointXYZ]] makeSacModel(int model_type, const shared_ptr[PointCloud[PointXYZ]]& cloud) except +

    bool sacModelIsNull(const shared_ptr[SampleConsensusModel[PointXYZ]]& model) except +

    shared_ptr[RandomSampleConsensus[PointXYZ]] makeRansac(const shared_ptr[SampleConsensusModel[PointXYZ]]& model) except +

    bool ransacComputeModel(RandomSampleConsensus[PointXYZ]& ransac) except +

    void ransacInliers(RandomSampleConsensus[PointXYZ]& ransac, vector[int]& out) except +

    void ransacCoefficients(RandomSampleConsensus[PointXYZ]& ransac, vector[float]& out) except +
