# Auto-generated by cppast2autopxd 0.1.0 from tracking_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ

cdef extern from "pcl/compat/tracking_args.h" namespace "pclcompat" nogil:
    cdef cppclass ParticleTracker:
        ParticleTracker(int particle_num, double step_noise, double resolution, double maximum_distance, int threads) except +
        void setReferenceCloud(const shared_ptr[PointCloud[PointXYZ]]& reference) except +
        void setInputCloud(const shared_ptr[PointCloud[PointXYZ]]& cloud) except +
        void compute() except +
        void result(float* out7) except +
        void resultTransform(float* out16) except +
        void alignedReference(vector[PointXYZ]& out) except +
        int particleNum() except +
