# Auto-generated by cppast2autopxd 0.1.0 from transform_args.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_types cimport PointXYZ, PointXYZI, PointXYZRGB, PointXYZRGBA

cdef extern from "pcl/compat/transform_args.h" namespace "pclcompat" nogil:
    void transformCloud(const PointCloud[PointXYZ]& in_, PointCloud[PointXYZ]& out, const float* matrix16) except +

    void transformCloud(const PointCloud[PointXYZI]& in_, PointCloud[PointXYZI]& out, const float* matrix16) except +

    void transformCloud(const PointCloud[PointXYZRGB]& in_, PointCloud[PointXYZRGB]& out, const float* matrix16) except +

    void transformCloud(const PointCloud[PointXYZRGBA]& in_, PointCloud[PointXYZRGBA]& out, const float* matrix16) except +

    bool isRigidTransform(const float* matrix16, float tolerance) except +
