# Auto-generated by cppast2autopxd 0.1.0 from range_image.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

cdef extern from "pcl/range_image/range_image.h" namespace "pcl" nogil:
    cdef cppclass RangeImage:
        pass
