# Auto-generated by cppast2autopxd 0.1.0 from kdtree_flann.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/kdtree/kdtree_flann.h" namespace "pcl" nogil:
    cdef cppclass KdTreeFLANN[PointT]:
        KdTreeFLANN() except +
        KdTreeFLANN(bool sorted) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setEpsilon(float eps) except +
        float getEpsilon() except +
        void setSortedResults(bool sorted) except +
        void setMinPts(int min_pts) except +
        int getMinPts() except +
        int nearestKSearch(const PointT& point, unsigned int k, vector[int]& k_indices, vector[float]& k_sqr_distances) except +
        int radiusSearch(const PointT& point, double radius, vector[int]& k_indices, vector[float]& k_sqr_distances) except +
        int radiusSearch(const PointT& point, double radius, vector[int]& k_indices, vector[float]& k_sqr_distances, unsigned int max_nn) except +
