"""python-pcl_skbuild: PCL (Point Cloud Library) Python bindings.

Built with scikit-build + CMake + Cython; the Cython extern declarations are
auto-generated by cppast2autopxd (see pxdgen/).
"""

from ._pointcloud import PointCloudXYZ

__all__ = ["PointCloudXYZ"]

__version__ = "0.1.0"
