"""python-pcl_skbuild: PCL (Point Cloud Library) Python bindings.

Built with scikit-build + CMake + Cython; the Cython extern declarations
are auto-generated by cppast2autopxd (see pxdgen/), the wrapper layer is
hand-written. The API follows sirokujira/python-pcl.
"""

import os.path

from ._pointcloud import PointCloud, PointCloudXYZ

__all__ = ["PointCloud", "PointCloudXYZ", "load", "save"]

__version__ = "0.1.0"


def load(path, format=None):
    """Load a point cloud from *path* (.pcd; ``format`` overrides the
    extension). Returns a :class:`PointCloud`."""
    fmt = _infer_format(path, format)
    if fmt != "pcd":
        raise ValueError(
            "unsupported format %r (only 'pcd' is wrapped so far)" % fmt
        )
    cloud = PointCloud()
    error = cloud._from_pcd_file(path)
    if error:
        raise IOError("error while loading %s (code %d)" % (path, error))
    return cloud


def save(cloud, path, format=None, binary=False):
    """Save :class:`PointCloud` *cloud* to *path* (.pcd; ``format``
    overrides the extension)."""
    fmt = _infer_format(path, format)
    if fmt != "pcd":
        raise ValueError(
            "unsupported format %r (only 'pcd' is wrapped so far)" % fmt
        )
    error = cloud._to_pcd_file(path, binary)
    if error:
        raise IOError("error while saving %s (code %d)" % (path, error))


def _infer_format(path, format):
    if format is not None:
        return format.lower()
    return os.path.splitext(path)[1][1:].lower()
