"""python-pcl_skbuild: PCL (Point Cloud Library) Python bindings.

Built with scikit-build + CMake + Cython; the Cython extern declarations
are auto-generated by cppast2autopxd (see pxdgen/), the wrapper layer is
hand-written. The API follows sirokujira/python-pcl.
"""

import contextlib
import gzip
import os
import os.path
import shutil
import tempfile

from ._pointcloud import PointCloud, PointCloudXYZ
from ._pointtypes import (
    PointCloud_Normal,
    PointCloud_PointXYZI,
    PointCloud_PointXYZRGB,
    PointCloud_PointXYZRGBA,
)
from ._features import (
    AVERAGE_3D_GRADIENT,
    AVERAGE_DEPTH_CHANGE,
    COVARIANCE_MATRIX,
    SIMPLE_3D_GRADIENT,
    DifferenceOfNormalsEstimation,
    FPFHEstimation,
    SHOTEstimation,
    IntegralImageNormalEstimation,
    MomentOfInertiaEstimation,
    NormalEstimation,
    VFHEstimation,
)
from ._octree import OctreePointCloudChangeDetector, OctreePointCloudSearch
from ._registration import (
    GeneralizedIterativeClosestPoint,
    IterativeClosestPoint,
    IterativeClosestPointNonLinear,
    NormalDistributionsTransform,
)
from ._surface import (
    ConcaveHull,
    ConvexHull,
    GreedyProjectionTriangulation,
    MovingLeastSquares,
)
from ._filters import (
    ApproximateVoxelGrid,
    CompareOp_EQ,
    CompareOp_GE,
    CompareOp_GT,
    CompareOp_LE,
    CompareOp_LT,
    ConditionAnd,
    ConditionalRemoval,
    CropBox,
    CropHull,
    ExtractIndices,
    FastBilateralFilter,
    PassThroughFilter,
    ProjectInliers,
    RadiusOutlierRemoval,
    RandomSample,
    StatisticalOutlierRemovalFilter,
    UniformSampling,
    VoxelGridFilter,
)
from ._keypoints import (
    CURVATURE,
    HARRIS,
    LOWE,
    NOBLE,
    TOMASI,
    HarrisKeypoint3D,
)
from ._grabber import HDLGrabber, PCDGrabber
from ._people import hog, hog_descriptor_size
from ._recognition import (
    GeometricConsistencyGrouping,
    Hough3DGrouping,
    match_descriptors,
)
from ._tracking import ParticleFilterTracker
from ._rangeimage import (
    CAMERA_FRAME,
    LASER_FRAME,
    RangeImage,
)
from ._sac import (
    RandomSampleConsensus,
    SampleConsensusModel,
    SampleConsensusModelCircle2D,
    SampleConsensusModelCircle3D,
    SampleConsensusModelLine,
    SampleConsensusModelPlane,
    SampleConsensusModelSphere,
    SampleConsensusModelStick,
)
from ._kdtree import KdTreeFLANN
from ._segmentation import (
    ConditionalEuclideanClustering,
    EuclideanClusterExtraction,
    MinCutSegmentation,
    ProgressiveMorphologicalFilter,
    Segmentation,
    SegmentationNormal,
    SAC_LMEDS,
    SAC_MLESAC,
    SAC_MSAC,
    SAC_PROSAC,
    SAC_RANSAC,
    SAC_RMSAC,
    SAC_RRANSAC,
    SACMODEL_CIRCLE2D,
    SACMODEL_CIRCLE3D,
    SACMODEL_CONE,
    SACMODEL_CYLINDER,
    SACMODEL_LINE,
    SACMODEL_NORMAL_PLANE,
    SACMODEL_NORMAL_SPHERE,
    SACMODEL_PARALLEL_LINE,
    SACMODEL_PARALLEL_PLANE,
    SACMODEL_PERPENDICULAR_PLANE,
    SACMODEL_PLANE,
    SACMODEL_SPHERE,
    SACMODEL_STICK,
    SACMODEL_TORUS,
    SACMODEL_PARALLEL_LINES,
    SACMODEL_REGISTRATION,
    SACMODEL_REGISTRATION_2D,
    SACMODEL_NORMAL_PARALLEL_PLANE,
    SACMODEL_ELLIPSE3D,
)

__all__ = [
    "PointCloud", "PointCloudXYZ", "load", "save",
    "PointCloud_Normal",
    "PointCloud_PointXYZI", "PointCloud_PointXYZRGB",
    "PointCloud_PointXYZRGBA",
    "load_XYZI", "load_XYZRGB", "load_XYZRGBA", "save_XYZRGBA",
    "VoxelGridFilter", "ApproximateVoxelGrid", "PassThroughFilter",
    "StatisticalOutlierRemovalFilter", "RadiusOutlierRemoval",
    "ExtractIndices", "CropBox", "CropHull", "ProjectInliers",
    "RandomSample",
    "UniformSampling", "ConditionAnd", "ConditionalRemoval",
    "FastBilateralFilter",
    "CompareOp_GT", "CompareOp_GE", "CompareOp_LT", "CompareOp_LE",
    "CompareOp_EQ",
    "HarrisKeypoint3D",
    "HARRIS", "NOBLE", "LOWE", "TOMASI", "CURVATURE",
    "KdTreeFLANN",
    "OctreePointCloudSearch", "OctreePointCloudChangeDetector",
    "NormalEstimation", "MomentOfInertiaEstimation", "VFHEstimation",
    "IntegralImageNormalEstimation", "DifferenceOfNormalsEstimation",
    "FPFHEstimation", "SHOTEstimation",
    "COVARIANCE_MATRIX", "AVERAGE_3D_GRADIENT", "AVERAGE_DEPTH_CHANGE",
    "SIMPLE_3D_GRADIENT",
    "MovingLeastSquares", "ConcaveHull", "ConvexHull",
    "GreedyProjectionTriangulation",
    "IterativeClosestPoint", "IterativeClosestPointNonLinear",
    "GeneralizedIterativeClosestPoint", "NormalDistributionsTransform",
    "PCDGrabber", "HDLGrabber",
    "RangeImage", "CAMERA_FRAME", "LASER_FRAME",
    "GeometricConsistencyGrouping", "Hough3DGrouping", "match_descriptors",
    "transform_cloud",
    "ParticleFilterTracker",
    "hog", "hog_descriptor_size",
    "RandomSampleConsensus", "SampleConsensusModel",
    "SampleConsensusModelPlane", "SampleConsensusModelLine",
    "SampleConsensusModelCircle2D", "SampleConsensusModelCircle3D",
    "SampleConsensusModelSphere", "SampleConsensusModelStick",
    "Segmentation", "SegmentationNormal", "EuclideanClusterExtraction",
    "ProgressiveMorphologicalFilter", "MinCutSegmentation",
    "ConditionalEuclideanClustering",
    "SAC_RANSAC", "SAC_LMEDS", "SAC_MSAC", "SAC_RRANSAC", "SAC_RMSAC",
    "SAC_MLESAC", "SAC_PROSAC",
    "SACMODEL_PLANE", "SACMODEL_LINE", "SACMODEL_CIRCLE2D",
    "SACMODEL_CIRCLE3D", "SACMODEL_SPHERE", "SACMODEL_CYLINDER",
    "SACMODEL_CONE", "SACMODEL_PARALLEL_LINE",
    "SACMODEL_PERPENDICULAR_PLANE", "SACMODEL_PARALLEL_PLANE",
    "SACMODEL_NORMAL_PLANE", "SACMODEL_NORMAL_SPHERE", "SACMODEL_STICK",
    "SACMODEL_TORUS", "SACMODEL_PARALLEL_LINES", "SACMODEL_REGISTRATION",
    "SACMODEL_REGISTRATION_2D", "SACMODEL_NORMAL_PARALLEL_PLANE",
    "SACMODEL_ELLIPSE3D",
]

__version__ = "0.1.0"


_LOADERS = {"pcd": "_from_pcd_file", "ply": "_from_ply_file"}
_SAVERS = {"pcd": "_to_pcd_file", "ply": "_to_ply_file"}


def load(path, format=None):
    """Load a point cloud from *path* (.pcd or .ply; ``format`` overrides
    the extension). Returns a :class:`PointCloud`.

    A ``.gz`` suffix is decompressed transparently — PCL's readers take a
    filename and open it themselves, so a gzipped cloud is unreadable
    without this (strawlab/python-pcl#131).
    """
    return _load(PointCloud, path, format)


def load_XYZI(path, format=None):
    """Load a :class:`PointCloud_PointXYZI` from *path*."""
    return _load(PointCloud_PointXYZI, path, format)


def load_XYZRGB(path, format=None):
    """Load a :class:`PointCloud_PointXYZRGB` from *path*."""
    return _load(PointCloud_PointXYZRGB, path, format)


def load_XYZRGBA(path, format=None):
    """Load a :class:`PointCloud_PointXYZRGBA` from *path*."""
    return _load(PointCloud_PointXYZRGBA, path, format)


def _load(cls, path, format):
    fmt = _infer_format(path, format)
    if fmt not in _LOADERS:
        raise ValueError(
            "unsupported format %r (wrapped: %s)"
            % (fmt, ", ".join(sorted(_LOADERS)))
        )

    cloud = cls()
    if _is_gzipped(path, format):
        with _decompressed(path, fmt) as plain:
            error = getattr(cloud, _LOADERS[fmt])(plain)
    else:
        error = getattr(cloud, _LOADERS[fmt])(path)
    if error:
        raise IOError("error while loading %s (code %d)" % (path, error))
    return cloud


def save(cloud, path, format=None, binary=False):
    """Save a cloud of any wrapped point type to *path* (.pcd or .ply;
    ``format`` overrides the extension).

    A ``.gz`` suffix compresses, mirroring :func:`load`.
    """
    fmt = _infer_format(path, format)
    if fmt not in _SAVERS:
        raise ValueError(
            "unsupported format %r (wrapped: %s)"
            % (fmt, ", ".join(sorted(_SAVERS)))
        )
    writer = getattr(cloud, _SAVERS[fmt])
    if _is_gzipped(path, format):
        error = _save_gzipped(writer, path, fmt, binary)
    else:
        error = writer(path, binary)
    if error:
        raise IOError("error while saving %s (code %d)" % (path, error))


def save_XYZRGBA(cloud, path, format=None, binary=False):
    """python-pcl spelling; `save` already handles every point type."""
    return save(cloud, path, format=format, binary=binary)


def _is_gzipped(path, format):
    return format is None and str(path).lower().endswith(".gz")


def _save_gzipped(writer, path, fmt, binary):
    """Write through a plain temporary file, then gzip it into place.

    The save-side counterpart of `_decompressed`, and needed for the same
    reason: PCL's writers take a filename and open it themselves, so they
    cannot compress. Without this, `save` left an UNCOMPRESSED cloud at a
    `.gz` path and `load` then refused to read it back.

    Compresses only on a successful write, so a failed save does not
    leave a truncated `.gz` behind.
    """
    handle, plain = tempfile.mkstemp(suffix="." + fmt)
    os.close(handle)
    try:
        error = writer(plain, binary)
        if not error:
            with open(plain, "rb") as src, gzip.open(path, "wb") as dst:
                shutil.copyfileobj(src, dst)
        return error
    finally:
        os.unlink(plain)


@contextlib.contextmanager
def _decompressed(path, fmt):
    """Yield a plain temporary copy of a gzipped cloud file."""
    handle, plain = tempfile.mkstemp(suffix="." + fmt)
    os.close(handle)
    try:
        with gzip.open(path, "rb") as src, open(plain, "wb") as dst:
            shutil.copyfileobj(src, dst)
        yield plain
    finally:
        os.unlink(plain)


def _infer_format(path, format):
    if format is not None:
        return format.lower()
    name = str(path)
    if name.lower().endswith(".gz"):
        name = name[: -len(".gz")]
    return os.path.splitext(name)[1][1:].lower()


def transform_cloud(cloud, matrix):
    """Return *cloud* moved by a 4x4 rigid transform.

    The free-function spelling of ``cloud.transform(matrix)``, for any
    wrapped point type. The matrix is what registration and recognition
    return, so a result applies directly:

        converged, matrix, _, _ = icp.icp(source, target)
        aligned = pcl.transform_cloud(source, matrix)
    """
    try:
        method = cloud.transform
    except AttributeError:
        raise TypeError(
            "transform_cloud() needs a point cloud, got %r"
            % type(cloud).__name__) from None
    return method(matrix)
