# distutils: language = c++
# cython: language_level=3
"""Filter wrappers, named after sirokujira/python-pcl (pcl/pxi/Filters/).

Reach them through the PointCloud factory methods — `make_voxel_grid_filter`,
`make_passthrough_filter`, `make_statistical_outlier_filter`,
`make_ApproximateVoxelGrid`, `make_RadiusOutlierRemoval` — or construct a
filter directly with the cloud as its argument.

The extern declarations come from src/pcl/pxd/filters/, auto-generated by
cppast2autopxd. This wrapper layer is hand-written by design.

Every filter follows the same shape: configure, then `filter()` returns a
new PointCloud. The whole PCL call runs under `nogil` — see bench/README.md
for why keeping the loop on the C++ side is the point of the binding.
"""

from cython.operator cimport dereference as deref

from libcpp cimport bool as cbool
from libcpp.string cimport string

from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.point_cloud cimport PointCloud as cPointCloud
# Aliased with a c-prefix: two of these wrapper classes carry the same
# name as the PCL class they wrap, and the cimport would otherwise be
# shadowed by the cdef class below.
from pcl.pxd.filters.voxel_grid cimport VoxelGrid as cVoxelGrid
from pcl.pxd.filters.approximate_voxel_grid cimport (
    ApproximateVoxelGrid as cApproximateVoxelGrid)
from pcl.pxd.filters.passthrough cimport PassThrough as cPassThrough
from pcl.pxd.filters.statistical_outlier_removal cimport (
    StatisticalOutlierRemoval as cStatisticalOutlierRemoval)
from pcl.pxd.filters.radius_outlier_removal cimport (
    RadiusOutlierRemoval as cRadiusOutlierRemoval)

from pcl._pointcloud cimport PointCloud


cdef string _tobytes(value):
    if isinstance(value, str):
        return <string> value.encode()
    return <string> value


cdef class VoxelGridFilter:
    """Downsample a cloud onto a voxel grid (pcl::VoxelGrid)."""

    cdef cVoxelGrid[PointXYZ]* me

    def __cinit__(self, PointCloud pc=None):
        self.me = new cVoxelGrid[PointXYZ]()
        if pc is not None:
            self.set_InputCloud(pc)

    def __dealloc__(self):
        del self.me
        self.me = NULL

    def set_InputCloud(self, PointCloud pc not None):
        self.me.setInputCloud(pc.thisptr_shared)

    def set_leaf_size(self, float x, float y, float z):
        """Set the voxel grid leaf size."""
        self.me.setLeafSize(x, y, z)

    def set_DownsampleAllData(self, bint downsample):
        self.me.setDownsampleAllData(downsample)

    def get_DownsampleAllData(self):
        return self.me.getDownsampleAllData()

    def set_SaveLeafLayout(self, bint save_leaf_layout):
        self.me.setSaveLeafLayout(save_leaf_layout)

    def get_SaveLeafLayout(self):
        return self.me.getSaveLeafLayout()

    def set_MinimumPointsNumberPerVoxel(self, unsigned int min_points):
        self.me.setMinimumPointsNumberPerVoxel(min_points)

    def get_MinimumPointsNumberPerVoxel(self):
        return self.me.getMinimumPointsNumberPerVoxel()

    def set_FilterFieldName(self, field_name):
        self.me.setFilterFieldName(_tobytes(field_name))

    def get_FilterFieldName(self):
        return self.me.getFilterFieldName().decode()

    def set_FilterLimits(self, double limit_min, double limit_max):
        self.me.setFilterLimits(limit_min, limit_max)

    def set_FilterLimitsNegative(self, bint limit_negative):
        self.me.setFilterLimitsNegative(limit_negative)

    def get_FilterLimitsNegative(self):
        return self.me.getFilterLimitsNegative()

    def filter(self):
        """Apply the filter and return the result as a new PointCloud."""
        cdef PointCloud pc = PointCloud()
        cdef cPointCloud[PointXYZ]* out = pc.ptr()
        with nogil:
            self.me.filter(deref(out))
        return pc


cdef class ApproximateVoxelGrid:
    """Faster, approximate voxel downsampling (pcl::ApproximateVoxelGrid)."""

    cdef cApproximateVoxelGrid[PointXYZ]* me

    def __cinit__(self, PointCloud pc=None):
        self.me = new cApproximateVoxelGrid[PointXYZ]()
        if pc is not None:
            self.set_InputCloud(pc)

    def __dealloc__(self):
        del self.me
        self.me = NULL

    def set_InputCloud(self, PointCloud pc not None):
        self.me.setInputCloud(pc.thisptr_shared)

    def set_leaf_size(self, float x, float y, float z):
        self.me.setLeafSize(x, y, z)

    def set_DownsampleAllData(self, bint downsample):
        self.me.setDownsampleAllData(downsample)

    def get_DownsampleAllData(self):
        return self.me.getDownsampleAllData()

    def filter(self):
        cdef PointCloud pc = PointCloud()
        cdef cPointCloud[PointXYZ]* out = pc.ptr()
        with nogil:
            self.me.filter(deref(out))
        return pc


cdef class PassThroughFilter:
    """Keep points whose field value falls inside a range
    (pcl::PassThrough)."""

    cdef cPassThrough[PointXYZ]* me

    def __cinit__(self, PointCloud pc=None):
        self.me = new cPassThrough[PointXYZ]()
        if pc is not None:
            self.set_InputCloud(pc)

    def __dealloc__(self):
        del self.me
        self.me = NULL

    def set_InputCloud(self, PointCloud pc not None):
        self.me.setInputCloud(pc.thisptr_shared)

    def set_filter_field_name(self, field_name):
        """Field to filter on, e.g. ``"z"``."""
        self.me.setFilterFieldName(_tobytes(field_name))

    def get_filter_field_name(self):
        return self.me.getFilterFieldName().decode()

    def set_filter_limits(self, float filter_min, float filter_max):
        self.me.setFilterLimits(filter_min, filter_max)

    def set_negative(self, bint negative):
        """Invert the selection: keep what would otherwise be removed."""
        self.me.setNegative(negative)

    def get_negative(self):
        return self.me.getNegative()

    def set_keep_organized(self, bint keep_organized):
        self.me.setKeepOrganized(keep_organized)

    def filter(self):
        cdef PointCloud pc = PointCloud()
        cdef cPointCloud[PointXYZ]* out = pc.ptr()
        with nogil:
            self.me.filter(deref(out))
        return pc


cdef class StatisticalOutlierRemovalFilter:
    """Remove points whose neighbour distances are statistical outliers
    (pcl::StatisticalOutlierRemoval)."""

    cdef cStatisticalOutlierRemoval[PointXYZ]* me

    def __cinit__(self, PointCloud pc=None):
        self.me = new cStatisticalOutlierRemoval[PointXYZ]()
        if pc is not None:
            self.set_InputCloud(pc)

    def __dealloc__(self):
        del self.me
        self.me = NULL

    def set_InputCloud(self, PointCloud pc not None):
        self.me.setInputCloud(pc.thisptr_shared)

    property mean_k:
        def __get__(self):
            return self.me.getMeanK()

        def __set__(self, int k):
            self.me.setMeanK(k)

    property negative:
        def __get__(self):
            return self.me.getNegative()

        def __set__(self, bint neg):
            self.me.setNegative(neg)

    property stddev_mul_thresh:
        def __get__(self):
            return self.me.getStddevMulThresh()

        def __set__(self, double thresh):
            self.me.setStddevMulThresh(thresh)

    def set_mean_k(self, int k):
        """Number of neighbours to average over."""
        self.me.setMeanK(k)

    def set_std_dev_mul_thresh(self, double std_mul):
        """Distance threshold, in standard deviations."""
        self.me.setStddevMulThresh(std_mul)

    def set_negative(self, bint negative):
        self.me.setNegative(negative)

    def filter(self):
        cdef PointCloud pc = PointCloud()
        cdef cPointCloud[PointXYZ]* out = pc.ptr()
        with nogil:
            self.me.filter(deref(out))
        return pc


cdef class RadiusOutlierRemoval:
    """Remove points with too few neighbours inside a radius
    (pcl::RadiusOutlierRemoval)."""

    cdef cRadiusOutlierRemoval[PointXYZ]* me

    def __cinit__(self, PointCloud pc=None):
        self.me = new cRadiusOutlierRemoval[PointXYZ]()
        if pc is not None:
            self.set_InputCloud(pc)

    def __dealloc__(self):
        del self.me
        self.me = NULL

    def set_InputCloud(self, PointCloud pc not None):
        self.me.setInputCloud(pc.thisptr_shared)

    def set_radius_search(self, double radius):
        self.me.setRadiusSearch(radius)

    def get_radius_search(self):
        return self.me.getRadiusSearch()

    def set_MinNeighborsInRadius(self, int min_pts):
        self.me.setMinNeighborsInRadius(min_pts)

    def get_MinNeighborsInRadius(self):
        return self.me.getMinNeighborsInRadius()

    def set_negative(self, bint negative):
        self.me.setNegative(negative)

    def filter(self):
        cdef PointCloud pc = PointCloud()
        cdef cPointCloud[PointXYZ]* out = pc.ptr()
        with nogil:
            self.me.filter(deref(out))
        return pc
