# distutils: language = c++
# cython: language_level=3
"""pcl.PointCloud — a cloud of pcl::PointXYZ points.

API modeled on sirokujira/python-pcl (pcl/pxi/PointCloud_PointXYZ.pxi):
construct from None / int / ndarray / sequence / another cloud,
from_array/to_array, from_list/to_list, resize, get_point, indexing,
and PCD file I/O (used by pcl.load / pcl.save).

The extern declarations come from src/pcl/pxd/, auto-generated by
cppast2autopxd (see pxdgen/).  This wrapper layer is hand-written by
design: ownership, error handling, and the pythonic API are decisions,
not projections of the C++ header.
"""

import numbers

from cython.operator cimport dereference as deref

from libcpp cimport bool as cbool
from libcpp.memory cimport shared_ptr
from libcpp.string cimport string

from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.point_cloud cimport PointCloud as cPointCloud
from pcl.pxd.io.pcd_io cimport loadPCDFile, savePCDFile


cdef string _topath(path):
    if isinstance(path, str):
        return <string> path.encode()
    return <string> path


cdef class PointCloud:
    """Represents a cloud of points in 3-d space.

    A point cloud can be initialized from either a NumPy ndarray of shape
    (n_points, 3), from a list of triples, from an integer n to create an
    "empty" cloud of n points, or from another PointCloud (copy).

    To load a point cloud from disk, use pcl.load.
    """

    # thisptr_shared and ptr() are declared in _pointcloud.pxd so the other
    # extension modules can reach them.

    def __cinit__(self, init=None):
        self.thisptr_shared.reset(new cPointCloud[PointXYZ]())
        if init is None:
            return
        elif isinstance(init, numbers.Integral):
            self.resize(init)
        elif isinstance(init, PointCloud):
            self.ptr()[0] = (<PointCloud> init).ptr()[0]
        else:
            try:
                self.from_array(init)
            except (TypeError, ValueError):
                self.from_list(init)

    cdef cPointCloud[PointXYZ]* ptr(self) except NULL:
        if not self.thisptr_shared:
            raise MemoryError("point cloud not allocated")
        return self.thisptr_shared.get()

    @property
    def width(self):
        """Width of the point cloud (number of columns)."""
        return self.ptr().width

    @property
    def height(self):
        """Height of the point cloud (1 for unorganized clouds)."""
        return self.ptr().height

    @property
    def size(self):
        """Number of points in the cloud."""
        return self.ptr().size()

    @property
    def is_dense(self):
        """True when the cloud contains no invalid (NaN/Inf) points."""
        return self.ptr().is_dense

    def __len__(self):
        return self.ptr().size()

    def __repr__(self):
        return "<PointCloud of %d points>" % self.size

    def empty(self):
        return self.ptr().empty()

    def clear(self):
        self.ptr().clear()
        self.ptr().width = 0
        self.ptr().height = 0

    def resize(self, Py_ssize_t x):
        if x < 0:
            raise MemoryError("can't resize PointCloud to negative size")
        self.ptr().resize(<size_t> x)
        self.ptr().width = <unsigned int> x
        self.ptr().height = 1

    def append(self, float x, float y, float z):
        """Append one point; keeps the cloud unorganized (height=1)."""
        cdef PointXYZ pt
        pt.x = x
        pt.y = y
        pt.z = z
        self.ptr().push_back(pt)
        self.ptr().width = <unsigned int> self.ptr().size()
        self.ptr().height = 1

    def from_array(self, float[:, :] arr not None):
        """Fill this object from a 2D float32 array of shape (n, 3)."""
        if arr.shape[1] != 3:
            raise ValueError(
                "array must have shape (n, 3), got (%d, %d)"
                % (arr.shape[0], arr.shape[1])
            )
        cdef Py_ssize_t npts = arr.shape[0]
        self.resize(npts)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i
        for i in range(npts):
            p = &(deref(c)[<size_t> i])
            p.x = arr[i, 0]
            p.y = arr[i, 1]
            p.z = arr[i, 2]

    def to_array(self):
        """Return this object as a 2D float32 numpy array of shape (n, 3)."""
        import numpy as np
        cdef Py_ssize_t n = <Py_ssize_t> self.ptr().size()
        result = np.empty((n, 3), dtype=np.float32)
        cdef float[:, ::1] view = result
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i
        for i in range(n):
            p = &(deref(c)[<size_t> i])
            view[i, 0] = p.x
            view[i, 1] = p.y
            view[i, 2] = p.z
        return result

    def from_list(self, _list):
        """Fill this pointcloud from a list of 3-tuples."""
        pts = list(_list)
        self.resize(len(pts))
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i = 0
        for x, y, z in pts:
            p = &(deref(c)[<size_t> i])
            p.x = x
            p.y = y
            p.z = z
            i += 1

    def to_list(self):
        """Return this object as a list of 3-tuples."""
        return [self.get_point(i) for i in range(self.ptr().size())]

    def get_point(self, Py_ssize_t index):
        """Return the point (3-tuple) at *index*."""
        return self.__getitem__(index)

    def set_point(self, Py_ssize_t index, float x, float y, float z):
        cdef Py_ssize_t i = self._normalize_index(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[<size_t> i])
        pt.x = x
        pt.y = y
        pt.z = z

    def __getitem__(self, index):
        cdef Py_ssize_t i = self._normalize_index(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[<size_t> i])
        return (pt.x, pt.y, pt.z)

    def __setitem__(self, index, value):
        x, y, z = value
        self.set_point(index, x, y, z)

    cdef Py_ssize_t _normalize_index(self, index) except -1:
        cdef Py_ssize_t n = <Py_ssize_t> self.ptr().size()
        cdef Py_ssize_t i = index
        if i < 0:
            i += n
        if i < 0 or i >= n:
            raise IndexError(index)
        return i

    # --- pickle -------------------------------------------------------
    def __reduce__(self):
        return type(self), (self.to_list(),)

    # --- file I/O (used by pcl.load / pcl.save) -----------------------
    def _from_pcd_file(self, path):
        """Fill this cloud from a .pcd file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = loadPCDFile[PointXYZ](s, deref(c))
        return error

    def _to_pcd_file(self, path, cbool binary=False):
        """Write this cloud to a .pcd file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = savePCDFile[PointXYZ](s, deref(c), binary)
        return error

    # --- algorithm factories (python-pcl compatible) -------------------
    #
    # The imports are deferred to call time on purpose. _filters, _kdtree
    # and _segmentation all cimport PointCloud from this module, so a
    # module-level import here would be circular. A Python-level import
    # inside the method has no such problem: by the time anyone calls a
    # factory, this module is fully initialised.

    def make_voxel_grid_filter(self):
        """Return a VoxelGridFilter with this cloud as input."""
        from pcl._filters import VoxelGridFilter
        return VoxelGridFilter(self)

    def make_ApproximateVoxelGrid(self):
        """Return an ApproximateVoxelGrid with this cloud as input."""
        from pcl._filters import ApproximateVoxelGrid
        return ApproximateVoxelGrid(self)

    def make_passthrough_filter(self):
        """Return a PassThroughFilter with this cloud as input."""
        from pcl._filters import PassThroughFilter
        return PassThroughFilter(self)

    def make_statistical_outlier_filter(self):
        """Return a StatisticalOutlierRemovalFilter with this cloud as
        input."""
        from pcl._filters import StatisticalOutlierRemovalFilter
        return StatisticalOutlierRemovalFilter(self)

    def make_RadiusOutlierRemoval(self):
        """Return a RadiusOutlierRemoval with this cloud as input."""
        from pcl._filters import RadiusOutlierRemoval
        return RadiusOutlierRemoval(self)

    def make_kdtree_flann(self):
        """Return a KdTreeFLANN indexing this cloud."""
        from pcl._kdtree import KdTreeFLANN
        return KdTreeFLANN(self)

    def make_segmenter(self):
        """Return a Segmentation with this cloud as input."""
        from pcl._segmentation import Segmentation
        return Segmentation(self)

    def make_EuclideanClusterExtraction(self):
        """Return a EuclideanClusterExtraction with this cloud as input."""
        from pcl._segmentation import EuclideanClusterExtraction
        return EuclideanClusterExtraction(self)


# Backwards-compatible name from the first iteration of this package.
PointCloudXYZ = PointCloud
