# distutils: language = c++
# cython: language_level=3
"""Minimal PCL wrapper: pcl.PointCloud<pcl::PointXYZ>.

The extern declarations come from src/pcl/pxd/, which are auto-generated by
cppast2autopxd (see pxdgen/).  This module is the compile-time proof that the
generated declarations line up with the real PCL headers.
"""

from cython.operator cimport dereference as deref

from libcpp.memory cimport shared_ptr

from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.point_cloud cimport PointCloud


cdef class PointCloudXYZ:
    """A point cloud of pcl::PointXYZ, held through pcl's shared_ptr."""

    cdef shared_ptr[PointCloud[PointXYZ]] thisptr

    def __cinit__(self):
        self.thisptr.reset(new PointCloud[PointXYZ]())

    cdef inline PointCloud[PointXYZ]* ptr(self) except NULL:
        if not self.thisptr:
            raise MemoryError("point cloud not allocated")
        return self.thisptr.get()

    @property
    def size(self):
        return self.ptr().size()

    @property
    def width(self):
        return self.ptr().width

    @property
    def height(self):
        return self.ptr().height

    @property
    def is_dense(self):
        return self.ptr().is_dense

    def __len__(self):
        return self.ptr().size()

    def empty(self):
        return self.ptr().empty()

    def clear(self):
        self.ptr().clear()

    def resize(self, size_t count):
        self.ptr().resize(count)

    def append(self, float x, float y, float z):
        cdef PointXYZ pt
        pt.x = x
        pt.y = y
        pt.z = z
        self.ptr().push_back(pt)

    def get_point(self, size_t index):
        if index >= self.ptr().size():
            raise IndexError(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[index])
        return (pt.x, pt.y, pt.z)

    def set_point(self, size_t index, float x, float y, float z):
        if index >= self.ptr().size():
            raise IndexError(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[index])
        pt.x = x
        pt.y = y
        pt.z = z

    def __getitem__(self, index):
        return self.get_point(self._normalize_index(index))

    def __setitem__(self, index, value):
        x, y, z = value
        self.set_point(self._normalize_index(index), x, y, z)

    def _normalize_index(self, index):
        cdef Py_ssize_t n = <Py_ssize_t> self.ptr().size()
        cdef Py_ssize_t i = index
        if i < 0:
            i += n
        if i < 0 or i >= n:
            raise IndexError(index)
        return i

    @classmethod
    def from_list(cls, points):
        cloud = cls()
        for x, y, z in points:
            cloud.append(x, y, z)
        return cloud

    def to_list(self):
        return [self.get_point(i) for i in range(self.ptr().size())]

    def __repr__(self):
        return (
            f"<PointCloudXYZ size={self.size} width={self.width} "
            f"height={self.height} dense={bool(self.is_dense)}>"
        )
