# distutils: language = c++
# cython: language_level=3
"""pcl.PointCloud — a cloud of pcl::PointXYZ points.

API modeled on sirokujira/python-pcl (pcl/pxi/PointCloud_PointXYZ.pxi):
construct from None / int / ndarray / sequence / another cloud,
from_array/to_array, from_list/to_list, resize, get_point, indexing,
and PCD file I/O (used by pcl.load / pcl.save).

The extern declarations come from src/pcl/pxd/, auto-generated by
cppast2autopxd (see pxdgen/).  This wrapper layer is hand-written by
design: ownership, error handling, and the pythonic API are decisions,
not projections of the C++ header.
"""

import numbers

from cython.operator cimport dereference as deref

from libcpp cimport bool as cbool
from libcpp.memory cimport shared_ptr
from libcpp.string cimport string

from pcl.pxd.point_types cimport PointXYZ
from pcl.pxd.point_cloud cimport PointCloud as cPointCloud
from pcl.pxd.io.pcd_io cimport loadPCDFile, savePCDFile
from pcl.pxd.io.ply_io cimport loadPLYFile, savePLYFile


cdef string _topath(path):
    if isinstance(path, str):
        return <string> path.encode()
    return <string> path


cdef class PointCloud:
    """Represents a cloud of points in 3-d space.

    A point cloud can be initialized from either a NumPy ndarray of shape
    (n_points, 3), from a list of triples, from an integer n to create an
    "empty" cloud of n points, or from another PointCloud (copy).

    To load a point cloud from disk, use pcl.load.
    """

    # thisptr_shared and ptr() are declared in _pointcloud.pxd so the other
    # extension modules can reach them.

    def __cinit__(self, init=None):
        self.thisptr_shared.reset(new cPointCloud[PointXYZ]())
        if init is None:
            return
        elif isinstance(init, numbers.Integral):
            self.resize(init)
        elif isinstance(init, PointCloud):
            self.ptr()[0] = (<PointCloud> init).ptr()[0]
        else:
            try:
                self.from_array(init)
            except (TypeError, ValueError):
                self.from_list(init)

    cdef cPointCloud[PointXYZ]* ptr(self) except NULL:
        if not self.thisptr_shared:
            raise MemoryError("point cloud not allocated")
        return self.thisptr_shared.get()

    @property
    def width(self):
        """Width of the point cloud (number of columns)."""
        return self.ptr().width

    @property
    def height(self):
        """Height of the point cloud (1 for unorganized clouds)."""
        return self.ptr().height

    @property
    def size(self):
        """Number of points in the cloud."""
        return self.ptr().size()

    @property
    def is_dense(self):
        """True when the cloud contains no invalid (NaN/Inf) points."""
        return self.ptr().is_dense

    def __len__(self):
        return self.ptr().size()

    def __repr__(self):
        return "<PointCloud of %d points>" % self.size

    def empty(self):
        return self.ptr().empty()

    def clear(self):
        self.ptr().clear()
        self.ptr().width = 0
        self.ptr().height = 0

    def resize(self, Py_ssize_t x):
        if x < 0:
            raise MemoryError("can't resize PointCloud to negative size")
        self.ptr().resize(<size_t> x)
        self.ptr().width = <unsigned int> x
        self.ptr().height = 1

    def append(self, float x, float y, float z):
        """Append one point; keeps the cloud unorganized (height=1)."""
        cdef PointXYZ pt
        pt.x = x
        pt.y = y
        pt.z = z
        self.ptr().push_back(pt)
        self.ptr().width = <unsigned int> self.ptr().size()
        self.ptr().height = 1

    def from_array(self, float[:, :] arr not None):
        """Fill this object from a 2D float32 array of shape (n, 3)."""
        if arr.shape[1] != 3:
            raise ValueError(
                "array must have shape (n, 3), got (%d, %d)"
                % (arr.shape[0], arr.shape[1])
            )
        cdef Py_ssize_t npts = arr.shape[0]
        self.resize(npts)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i
        for i in range(npts):
            p = &(deref(c)[<size_t> i])
            p.x = arr[i, 0]
            p.y = arr[i, 1]
            p.z = arr[i, 2]

    def to_array(self):
        """Return this object as a 2D float32 numpy array of shape (n, 3)."""
        import numpy as np
        cdef Py_ssize_t n = <Py_ssize_t> self.ptr().size()
        result = np.empty((n, 3), dtype=np.float32)
        cdef float[:, ::1] view = result
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i
        for i in range(n):
            p = &(deref(c)[<size_t> i])
            view[i, 0] = p.x
            view[i, 1] = p.y
            view[i, 2] = p.z
        return result

    @property
    def is_organized(self):
        """True for a cloud laid out as a depth image (height > 1)."""
        return self.ptr().height > 1

    def from_organized_array(self, float[:, :, :] arr not None):
        """Fill from a ``(height, width, 3)`` float32 array.

        An organized cloud keeps the sensor's pixel grid, which is what
        `FastBilateralFilter` and `IntegralImageNormalEstimation` need —
        they work on the depth image, and silently do nothing without it.
        """
        if arr.shape[2] != 3:
            raise ValueError(
                "array must have shape (height, width, 3), got "
                "(%d, %d, %d)" % (arr.shape[0], arr.shape[1], arr.shape[2]))
        cdef Py_ssize_t height = arr.shape[0]
        cdef Py_ssize_t width = arr.shape[1]
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        c.resize(<size_t> (width * height))
        c.width = <unsigned int> width
        c.height = <unsigned int> height
        cdef PointXYZ* p
        cdef Py_ssize_t row, col, i
        for row in range(height):
            for col in range(width):
                i = row * width + col
                p = &(deref(c)[<size_t> i])
                p.x = arr[row, col, 0]
                p.y = arr[row, col, 1]
                p.z = arr[row, col, 2]

    def to_organized_array(self):
        """Return a ``(height, width, 3)`` float32 array.

        Raises for an unorganized cloud, which has no grid to return.
        """
        if not self.is_organized:
            raise ValueError(
                "cloud is not organized (height=%d); use to_array()"
                % self.ptr().height)
        return self.to_array().reshape(
            self.ptr().height, self.ptr().width, 3)

    def from_list(self, _list):
        """Fill this pointcloud from a list of 3-tuples."""
        pts = list(_list)
        self.resize(len(pts))
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef PointXYZ* p
        cdef Py_ssize_t i = 0
        for x, y, z in pts:
            p = &(deref(c)[<size_t> i])
            p.x = x
            p.y = y
            p.z = z
            i += 1

    def to_list(self):
        """Return this object as a list of 3-tuples."""
        return [self.get_point(i) for i in range(self.ptr().size())]

    def get_point(self, Py_ssize_t index):
        """Return the point (3-tuple) at *index*."""
        return self.__getitem__(index)

    def set_point(self, Py_ssize_t index, float x, float y, float z):
        cdef Py_ssize_t i = self._normalize_index(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[<size_t> i])
        pt.x = x
        pt.y = y
        pt.z = z

    def __getitem__(self, index):
        cdef Py_ssize_t i = self._normalize_index(index)
        cdef PointXYZ* pt = &(deref(self.ptr())[<size_t> i])
        return (pt.x, pt.y, pt.z)

    def __setitem__(self, index, value):
        x, y, z = value
        self.set_point(index, x, y, z)

    cdef Py_ssize_t _normalize_index(self, index) except -1:
        cdef Py_ssize_t n = <Py_ssize_t> self.ptr().size()
        cdef Py_ssize_t i = index
        if i < 0:
            i += n
        if i < 0 or i >= n:
            raise IndexError(index)
        return i

    # --- pickle -------------------------------------------------------
    def __reduce__(self):
        return type(self), (self.to_list(),)

    # --- file I/O (used by pcl.load / pcl.save) -----------------------
    def _from_pcd_file(self, path):
        """Fill this cloud from a .pcd file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = loadPCDFile[PointXYZ](s, deref(c))
        return error

    def _to_pcd_file(self, path, cbool binary=False):
        """Write this cloud to a .pcd file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = savePCDFile[PointXYZ](s, deref(c), binary)
        return error

    def _from_ply_file(self, path):
        """Fill this cloud from a .ply file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = loadPLYFile[PointXYZ](s, deref(c))
        return error

    def _to_ply_file(self, path, cbool binary=False):
        """Write this cloud to a .ply file; returns PCL's error code."""
        cdef string s = _topath(path)
        cdef cPointCloud[PointXYZ]* c = self.ptr()
        cdef int error
        with nogil:
            error = savePLYFile[PointXYZ](s, deref(c), binary)
        return error

    # --- algorithm factories (python-pcl compatible) -------------------
    #
    # The imports are deferred to call time on purpose. _filters, _kdtree
    # and _segmentation all cimport PointCloud from this module, so a
    # module-level import here would be circular. A Python-level import
    # inside the method has no such problem: by the time anyone calls a
    # factory, this module is fully initialised.

    def make_voxel_grid_filter(self):
        """Return a VoxelGridFilter with this cloud as input."""
        from pcl._filters import VoxelGridFilter
        return VoxelGridFilter(self)

    def make_ApproximateVoxelGrid(self):
        """Return an ApproximateVoxelGrid with this cloud as input."""
        from pcl._filters import ApproximateVoxelGrid
        return ApproximateVoxelGrid(self)

    def make_passthrough_filter(self):
        """Return a PassThroughFilter with this cloud as input."""
        from pcl._filters import PassThroughFilter
        return PassThroughFilter(self)

    def make_statistical_outlier_filter(self):
        """Return a StatisticalOutlierRemovalFilter with this cloud as
        input."""
        from pcl._filters import StatisticalOutlierRemovalFilter
        return StatisticalOutlierRemovalFilter(self)

    def make_RadiusOutlierRemoval(self):
        """Return a RadiusOutlierRemoval with this cloud as input."""
        from pcl._filters import RadiusOutlierRemoval
        return RadiusOutlierRemoval(self)

    def make_kdtree_flann(self):
        """Return a KdTreeFLANN indexing this cloud."""
        from pcl._kdtree import KdTreeFLANN
        return KdTreeFLANN(self)

    def make_segmenter(self):
        """Return a Segmentation with this cloud as input."""
        from pcl._segmentation import Segmentation
        return Segmentation(self)

    def make_EuclideanClusterExtraction(self):
        """Return a EuclideanClusterExtraction with this cloud as input."""
        from pcl._segmentation import EuclideanClusterExtraction
        return EuclideanClusterExtraction(self)

    def make_segmenter_normals(self):
        """Return a SegmentationNormal with this cloud as input."""
        from pcl._segmentation import SegmentationNormal
        return SegmentationNormal(self)

    def make_ProgressiveMorphologicalFilter(self):
        """Return a ProgressiveMorphologicalFilter with this cloud."""
        from pcl._segmentation import ProgressiveMorphologicalFilter
        return ProgressiveMorphologicalFilter(self)

    def make_ConditionAnd(self):
        """Return an empty ConditionAnd to add comparisons to."""
        from pcl._filters import ConditionAnd
        return ConditionAnd()

    def make_ConditionalRemoval(self, condition):
        """Return a ConditionalRemoval using *condition* on this cloud."""
        from pcl._filters import ConditionalRemoval
        return ConditionalRemoval(condition, self)

    def make_ExtractIndices(self):
        """Return an ExtractIndices with this cloud as input."""
        from pcl._filters import ExtractIndices
        return ExtractIndices(self)

    def make_cropbox(self):
        """Return a CropBox with this cloud as input."""
        from pcl._filters import CropBox
        return CropBox(self)

    def make_ProjectInliers(self):
        """Return a ProjectInliers with this cloud as input."""
        from pcl._filters import ProjectInliers
        return ProjectInliers(self)

    def make_RandomSample(self):
        """Return a RandomSample with this cloud as input."""
        from pcl._filters import RandomSample
        return RandomSample(self)

    def make_UniformSampling(self):
        """Return a UniformSampling with this cloud as input."""
        from pcl._filters import UniformSampling
        return UniformSampling(self)

    def make_RangeImage(self, float angular_resolution=0.008726646):
        """Return a RangeImage rendered from this cloud.

        The default resolution is 0.5 degrees in radians, PCL's own.
        """
        from pcl._rangeimage import RangeImage
        return RangeImage(self, angular_resolution)

    def make_HarrisKeypoint3D(self):
        """Return a HarrisKeypoint3D with this cloud as input."""
        from pcl._keypoints import HarrisKeypoint3D
        return HarrisKeypoint3D(self)

    def make_octreeSearch(self, double resolution):
        """Return an OctreePointCloudSearch built from this cloud."""
        from pcl._octree import OctreePointCloudSearch
        return OctreePointCloudSearch(resolution, self)

    def make_octreeChangeDetector(self, double resolution):
        """Return an OctreePointCloudChangeDetector holding this cloud."""
        from pcl._octree import OctreePointCloudChangeDetector
        return OctreePointCloudChangeDetector(resolution, self)

    def make_VFHEstimation(self):
        """Return a VFHEstimation with this cloud as input."""
        from pcl._features import VFHEstimation
        return VFHEstimation(self)

    def make_IntegralImageNormalEstimation(self):
        """Return an IntegralImageNormalEstimation with this cloud."""
        from pcl._features import IntegralImageNormalEstimation
        return IntegralImageNormalEstimation(self)

    def make_ConditionalEuclideanClustering(self):
        """Return a ConditionalEuclideanClustering with this cloud."""
        from pcl._segmentation import ConditionalEuclideanClustering
        return ConditionalEuclideanClustering(self)

    def make_FastBilateralFilter(self):
        """Return a FastBilateralFilter with this cloud as input."""
        from pcl._filters import FastBilateralFilter
        return FastBilateralFilter(self)

    def make_MinCutSegmentation(self):
        """Return a MinCutSegmentation with this cloud as input."""
        from pcl._segmentation import MinCutSegmentation
        return MinCutSegmentation(self)

    def make_NormalEstimation(self):
        """Return a NormalEstimation with this cloud as input."""
        from pcl._features import NormalEstimation
        return NormalEstimation(self)

    def make_DifferenceOfNormalsEstimation(self):
        """Return a DifferenceOfNormalsEstimation with this cloud."""
        from pcl._features import DifferenceOfNormalsEstimation
        return DifferenceOfNormalsEstimation(self)

    def make_MomentOfInertiaEstimation(self):
        """Return a MomentOfInertiaEstimation with this cloud as input."""
        from pcl._features import MomentOfInertiaEstimation
        return MomentOfInertiaEstimation(self)

    def make_moving_least_squares(self):
        """Return a MovingLeastSquares with this cloud as input."""
        from pcl._surface import MovingLeastSquares
        return MovingLeastSquares(self)

    def make_crophull(self):
        """Return a CropHull with this cloud as input."""
        from pcl._filters import CropHull
        return CropHull(self)

    def make_GreedyProjectionTriangulation(self):
        """Return a GreedyProjectionTriangulation."""
        from pcl._surface import GreedyProjectionTriangulation
        return GreedyProjectionTriangulation()

    def make_ConcaveHull(self):
        """Return a ConcaveHull with this cloud as input."""
        from pcl._surface import ConcaveHull
        return ConcaveHull(self)

    def make_ConvexHull(self):
        """Return a ConvexHull with this cloud as input."""
        from pcl._surface import ConvexHull
        return ConvexHull(self)

    def make_IterativeClosestPoint(self):
        """Return an IterativeClosestPoint."""
        from pcl._registration import IterativeClosestPoint
        return IterativeClosestPoint()

    def make_IterativeClosestPointNonLinear(self):
        """Return an IterativeClosestPointNonLinear."""
        from pcl._registration import IterativeClosestPointNonLinear
        return IterativeClosestPointNonLinear()

    def make_GeneralizedIterativeClosestPoint(self):
        """Return a GeneralizedIterativeClosestPoint."""
        from pcl._registration import GeneralizedIterativeClosestPoint
        return GeneralizedIterativeClosestPoint()

    def make_NormalDistributionsTransform(self):
        """Return a NormalDistributionsTransform."""
        from pcl._registration import NormalDistributionsTransform
        return NormalDistributionsTransform()


cdef PointCloud wrap_cloud(shared_ptr[cPointCloud[PointXYZ]] ptr):
    """Wrap an existing pcl::PointCloud without copying its points.

    __cinit__ always runs and allocates a cloud; assigning over the
    shared_ptr releases that one immediately. The alternative — a second
    constructor path — would be more code for one freed allocation.
    """
    cdef PointCloud pc = PointCloud()
    pc.thisptr_shared = ptr
    return pc


# Backwards-compatible name from the first iteration of this package.
PointCloudXYZ = PointCloud
