# Auto-generated by cppast2autopxd 0.1.0 from approximate_voxel_grid.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/approximate_voxel_grid.h" namespace "pcl" nogil:
    cdef cppclass ApproximateVoxelGrid[PointT]:
        ApproximateVoxelGrid() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setLeafSize(float lx, float ly, float lz) except +
        void setDownsampleAllData(bool downsample) except +
        bool getDownsampleAllData() except +
