# Auto-generated by cppast2autopxd 0.1.0 from conditional_removal.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/conditional_removal.h" namespace "pcl" nogil:
    cdef cppclass ConditionAnd[PointT]:
        ConditionAnd() except +

    cdef cppclass ConditionalRemoval[PointT]:
        ConditionalRemoval() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setKeepOrganized(bool keep_organized) except +
        bool getKeepOrganized() except +
        void setUserFilterValue(float value) except +
