# Auto-generated by cppast2autopxd 0.1.0 from crop_hull.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.vertices cimport Vertices

cdef extern from "pcl/filters/crop_hull.h" namespace "pcl" nogil:
    cdef cppclass CropHull[PointT]:
        CropHull() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setNegative(bool negative) except +
        void setHullCloud(shared_ptr[PointCloud[PointT]] points) except +
        void setHullIndices(const vector[Vertices]& polygons) except +
        void setDim(int dim) except +
        void setCropOutside(bool crop_outside) except +
