# Auto-generated by cppast2autopxd 0.1.0 from extract_indices.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud
from pcl.pxd.point_indices cimport PointIndices

cdef extern from "pcl/filters/extract_indices.h" namespace "pcl" nogil:
    cdef cppclass ExtractIndices[PointT]:
        ExtractIndices() except +
        ExtractIndices(bool extract_removed_indices) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void setIndices(const shared_ptr[PointIndices]& indices) except +
        void filter(PointCloud[PointT]& output) except +
        void setNegative(bool negative) except +
        bool getNegative() except +
        void setKeepOrganized(bool keep_organized) except +
        void setUserFilterValue(float value) except +
