# Auto-generated by cppast2autopxd 0.1.0 from fast_bilateral.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/fast_bilateral.h" namespace "pcl" nogil:
    cdef cppclass FastBilateralFilter[PointT]:
        FastBilateralFilter() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setSigmaS(float sigma_s) except +
        float getSigmaS() except +
        void setSigmaR(float sigma_r) except +
        float getSigmaR() except +
