# Auto-generated by cppast2autopxd 0.1.0 from passthrough.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.string cimport string
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/passthrough.h" namespace "pcl" nogil:
    cdef cppclass PassThrough[PointT]:
        PassThrough() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setNegative(bool negative) except +
        bool getNegative() except +
        void setKeepOrganized(bool keep_organized) except +
        bool getKeepOrganized() except +
        void setFilterFieldName(const string& field_name) except +
        string getFilterFieldName() except +
        void setFilterLimits(const float& limit_min, const float& limit_max) except +
