# Auto-generated by cppast2autopxd 0.1.0 from project_inliers.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.model_coefficients cimport ModelCoefficients
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/project_inliers.h" namespace "pcl" nogil:
    cdef cppclass ProjectInliers[PointT]:
        ProjectInliers() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setModelType(int model) except +
        int getModelType() except +
        void setModelCoefficients(const shared_ptr[ModelCoefficients]& model) except +
        void setCopyAllData(bool val) except +
        bool getCopyAllData() except +
