# Auto-generated by cppast2autopxd 0.1.0 from radius_outlier_removal.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/radius_outlier_removal.h" namespace "pcl" nogil:
    cdef cppclass RadiusOutlierRemoval[PointT]:
        RadiusOutlierRemoval() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setNegative(bool negative) except +
        bool getNegative() except +
        void setKeepOrganized(bool keep_organized) except +
        void setRadiusSearch(double radius) except +
        double getRadiusSearch() except +
        void setMinNeighborsInRadius(int min_pts) except +
        int getMinNeighborsInRadius() except +
