# Auto-generated by cppast2autopxd 0.1.0 from random_sample.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/random_sample.h" namespace "pcl" nogil:
    cdef cppclass RandomSample[PointT]:
        RandomSample() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setNegative(bool negative) except +
        void setSample(unsigned int sample) except +
        unsigned int getSample() except +
        void setSeed(unsigned int seed) except +
        unsigned int getSeed() except +
