# Auto-generated by cppast2autopxd 0.1.0 from uniform_sampling.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/uniform_sampling.h" namespace "pcl" nogil:
    cdef cppclass UniformSampling[PointT]:
        UniformSampling() except +
        UniformSampling(bool extract_removed_indices) except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setRadiusSearch(double radius) except +
