# Auto-generated by cppast2autopxd 0.1.0 from voxel_grid.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.string cimport string
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/filters/voxel_grid.h" namespace "pcl" nogil:
    cdef cppclass VoxelGrid[PointT]:
        VoxelGrid() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void filter(PointCloud[PointT]& output) except +
        void setLeafSize(float lx, float ly, float lz) except +
        void setDownsampleAllData(bool downsample) except +
        bool getDownsampleAllData() except +
        void setMinimumPointsNumberPerVoxel(unsigned int min_points_per_voxel) except +
        unsigned int getMinimumPointsNumberPerVoxel() except +
        void setSaveLeafLayout(bool save_leaf_layout) except +
        bool getSaveLeafLayout() except +
        void setFilterFieldName(const string& field_name) except +
        string getFilterFieldName() except +
        void setFilterLimits(const double& limit_min, const double& limit_max) except +
        void setFilterLimitsNegative(const bool limit_negative) except +
        bool getFilterLimitsNegative() except +
