# Auto-generated by cppast2autopxd 0.1.0 from don.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/don.h" namespace "pcl" nogil:
    cdef cppclass DifferenceOfNormalsEstimation[PointInT, PointNT, PointOutT]:
        DifferenceOfNormalsEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void computeFeature(PointCloud[PointOutT]& output) except +
        void setNormalScaleSmall(const shared_ptr[PointCloud[PointNT]]& normals) except +
        void setNormalScaleLarge(const shared_ptr[PointCloud[PointNT]]& normals) except +
        bool initCompute() except +
