# Auto-generated by cppast2autopxd 0.1.0 from fpfh.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/fpfh.h" namespace "pcl" nogil:
    cdef cppclass FPFHEstimation[PointInT, PointNT, PointOutT]:
        FPFHEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setInputNormals(const shared_ptr[PointCloud[PointNT]]& normals) except +
        void setKSearch(int k) except +
        int getKSearch() except +
        void setRadiusSearch(double radius) except +
        double getRadiusSearch() except +
        void compute(PointCloud[PointOutT]& output) except +
