# Auto-generated by cppast2autopxd 0.1.0 from integral_image_normal.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/integral_image_normal.h" namespace "pcl" nogil:
    cdef cppclass IntegralImageNormalEstimation[PointInT, PointOutT]:
        IntegralImageNormalEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void compute(PointCloud[PointOutT]& output) except +
        void setMaxDepthChangeFactor(float max_depth_change_factor) except +
        void setNormalSmoothingSize(float normal_smoothing_size) except +
        void setDepthDependentSmoothing(bool use_depth_dependent_smoothing) except +
        void setRectSize(int width, int height) except +
        void setViewPoint(float vpx, float vpy, float vpz) except +
