# Auto-generated by cppast2autopxd 0.1.0 from moment_of_inertia_estimation.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from libcpp.vector cimport vector
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/moment_of_inertia_estimation.h" namespace "pcl" nogil:
    cdef cppclass MomentOfInertiaEstimation[PointT]:
        MomentOfInertiaEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointT]]& cloud) except +
        void compute() except +
        void setAngleStep(float step) except +
        float getAngleStep() except +
        void setNormalizePointMassFlag(bool need_to_normalize) except +
        bool getNormalizePointMassFlag() except +
        void setPointMass(float point_mass) except +
        float getPointMass() except +
        bool getMomentOfInertia(vector[float]& moment_of_inertia) except +
        bool getEccentricity(vector[float]& eccentricity) except +
