# Auto-generated by cppast2autopxd 0.1.0 from normal_3d.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/normal_3d.h" namespace "pcl" nogil:
    cdef cppclass NormalEstimation[PointInT, PointOutT]:
        NormalEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setKSearch(int k) except +
        int getKSearch() except +
        void setRadiusSearch(double radius) except +
        double getRadiusSearch() except +
        void compute(PointCloud[PointOutT]& output) except +
        void setViewPoint(float vpx, float vpy, float vpz) except +
        void useSensorOriginAsViewPoint() except +
