# Auto-generated by cppast2autopxd 0.1.0 from vfh.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/features/vfh.h" namespace "pcl" nogil:
    cdef cppclass VFHEstimation[PointInT, PointNT, PointOutT]:
        VFHEstimation() except +
        void setInputCloud(const shared_ptr[PointCloud[PointInT]]& cloud) except +
        void setKSearch(int k) except +
        void setRadiusSearch(double radius) except +
        void compute(PointCloud[PointOutT]& output) except +
        void setInputNormals(const shared_ptr[PointCloud[PointNT]]& normals) except +
        void setViewPoint(float vpx, float vpy, float vpz) except +
        void setNormalizeBins(bool normalize) except +
        void setNormalizeDistance(bool normalize) except +
        void setFillSizeComponent(bool fill_size) except +
