# Auto-generated by cppast2autopxd 0.1.0 from method_types.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

cdef extern from "pcl/sample_consensus/method_types.h" namespace "pcl" nogil:
    const int SAC_RANSAC

    const int SAC_LMEDS

    const int SAC_MSAC

    const int SAC_RRANSAC

    const int SAC_RMSAC

    const int SAC_MLESAC

    const int SAC_PROSAC
