# Auto-generated by cppast2autopxd 0.1.0 from model_types.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

cdef extern from "pcl/sample_consensus/model_types.h" namespace "pcl" nogil:
    cdef enum SacModel:
        SACMODEL_PLANE = 0
        SACMODEL_LINE = 1
        SACMODEL_CIRCLE2D = 2
        SACMODEL_CIRCLE3D = 3
        SACMODEL_SPHERE = 4
        SACMODEL_CYLINDER = 5
        SACMODEL_CONE = 6
        SACMODEL_TORUS = 7
        SACMODEL_PARALLEL_LINE = 8
        SACMODEL_PERPENDICULAR_PLANE = 9
        SACMODEL_PARALLEL_LINES = 10
        SACMODEL_NORMAL_PLANE = 11
        SACMODEL_NORMAL_SPHERE = 12
        SACMODEL_REGISTRATION = 13
        SACMODEL_REGISTRATION_2D = 14
        SACMODEL_PARALLEL_PLANE = 15
        SACMODEL_NORMAL_PARALLEL_PLANE = 16
        SACMODEL_STICK = 17
        SACMODEL_ELLIPSE3D = 18
