# Auto-generated by cppast2autopxd 0.1.0 from ransac.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

cdef extern from "pcl/sample_consensus/ransac.h" namespace "pcl" nogil:
    cdef cppclass RandomSampleConsensus[PointT]:
        void setDistanceThreshold(double threshold) except +
        double getDistanceThreshold() except +
        void setMaxIterations(int max_iterations) except +
        int getMaxIterations() except +
        void setProbability(double probability) except +
        double getProbability() except +
