# Auto-generated by cppast2autopxd 0.1.0 from sac_model.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

cdef extern from "pcl/sample_consensus/sac_model.h" namespace "pcl" nogil:
    cdef cppclass SampleConsensusModel[PointT]:
        pass
