# Auto-generated by cppast2autopxd 0.1.0 from gicp.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/registration/gicp.h" namespace "pcl" nogil:
    cdef cppclass GeneralizedIterativeClosestPoint[PointSource, PointTarget]:
        GeneralizedIterativeClosestPoint() except +
        void setInputSource(const shared_ptr[PointCloud[PointSource]]& cloud) except +
        void setInputTarget(const shared_ptr[PointCloud[PointTarget]]& cloud) except +
        void setMaximumIterations(int nr_iterations) except +
        int getMaximumIterations() except +
        void setMaxCorrespondenceDistance(double distance_threshold) except +
        double getMaxCorrespondenceDistance() except +
        void setTransformationEpsilon(double epsilon) except +
        double getTransformationEpsilon() except +
        void setEuclideanFitnessEpsilon(double epsilon) except +
        double getEuclideanFitnessEpsilon() except +
        void align(PointCloud[PointSource]& output) except +
        bool hasConverged() except +
        double getFitnessScore() except +
        void setRotationEpsilon(double epsilon) except +
        double getRotationEpsilon() except +
        void setCorrespondenceRandomness(int k) except +
        int getCorrespondenceRandomness() except +
        void setMaximumOptimizerIterations(int max_iterations) except +
        int getMaximumOptimizerIterations() except +
