# Auto-generated by cppast2autopxd 0.1.0 from ndt.h.
# Do not edit by hand; re-run the generator instead.

# distutils: language = c++

from libcpp cimport bool
from libcpp.memory cimport shared_ptr
from pcl.pxd.point_cloud cimport PointCloud

cdef extern from "pcl/registration/ndt.h" namespace "pcl" nogil:
    cdef cppclass NormalDistributionsTransform[PointSource, PointTarget]:
        NormalDistributionsTransform() except +
        void setInputSource(const shared_ptr[PointCloud[PointSource]]& cloud) except +
        void setInputTarget(const shared_ptr[PointCloud[PointTarget]]& cloud) except +
        void setMaximumIterations(int nr_iterations) except +
        int getMaximumIterations() except +
        void setTransformationEpsilon(double epsilon) except +
        double getTransformationEpsilon() except +
        void setEuclideanFitnessEpsilon(double epsilon) except +
        void align(PointCloud[PointSource]& output) except +
        bool hasConverged() except +
        double getFitnessScore() except +
        void setResolution(float resolution) except +
        float getResolution() except +
        void setStepSize(double step_size) except +
        double getStepSize() except +
        void setOulierRatio(double outlier_ratio) except +
        double getOulierRatio() except +
        double getTransformationProbability() except +
        int getFinalNumIteration() except +
